name: Build Masa Log Viewer

on:
  push:
    tags:
      - 'v*'  # 每當你推送 tag（例如 v1.0.0）就會執行

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt pyinstaller
      - run: pyinstaller --windowed --onefile main.py
      - uses: actions/upload-artifact@v4
        with:
          name: masa-log-windows
          path: dist/*.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt py2app
      - run: python setup.py py2app
      - uses: actions/upload-artifact@v4
        with:
          name: masa-log-macos
          path: dist/*.app
